###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: hexagonal-arquiteture-redis

    postgres:
      image: postgres:11.1-alpine
      container_name: hexagonal-arquiteture-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=php
      ports:
        - "8892:5432"

    webserver:
      image: nginx:alpine
      container_name: hexagonal-arquiteture-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: hexagonal-arquiteture-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      ports:
        - "8888:8888"
